language: cpp

service:
  - mysql

cache:
  - /usr/local/opt/boost
  - /usr/local/include
  - /usr/local/lib
  - /usr/local/Cellar
  - /usr/lib
  - /usr/include

matrix:
  global:
    - MYSQL_USER='travis'
    - MYSQL_PASSWORD='travis'
    - MYSQL_DATABASE='horizon'
  include:
    #
    # LINUX GCC BUILDS
    #
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - TOOLSET="gcc"
        - BUILD_TYPE="Debug"
        - COMPILE_OPTIONS="-DWITH_CORE_DEBUG=1 -DWITH_STACK_CHECK=1"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - TOOLSET="gcc"
        - BUILD_TYPE="Debug"
        - COMPILE_OPTIONS="-DWITH_CORE_DEBUG=1 -DWITH_STACK_CHECK=1"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - TOOLSET="gcc"
        - BUILD_TYPE="Debug"
        - COMPILE_OPTIONS="-DWITH_CORE_DEBUG=1 -DWITH_STACK_CHECK=1"
    #
    # OSX Debug and Sanitization
    #
    - os: osx
      osx_image: xcode12.2
      env:
        - TOOLSET="clang"
        - BUILD_TYPE="Debug"
        - COMPILE_OPTIONS="-DWITH_WARNINGS=1 -DWITH_CORE_DEBUG=1"
    # - os: osx
    #   osx_image: xcode12.2
    #   env:
    #     - TOOLSET="clang"
    #     - BUILD_TYPE="Debug"
    #     - COMPILE_OPTIONS="-DWITH_ASAN=1 -DWITH_WARNINGS=1 -DWITH_CORE_DEBUG=1"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      pushd install && chmod +x ubuntu.sh && ./ubuntu.sh;
      popd;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pushd install && chmod +x osx.sh && ./osx.sh;
      popd;
    fi

script:
  - pushd .
  - echo "Initiating Horizon build...";
  - mkdir build;
  - pushd build;
  #
  # Install Linux
  #
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cmake ../ -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${COMPILE_OPTIONS} -DWITH_COVERAGE=1 -DWITH_TESTS=1 -DBOOST_INCLUDEDIR=/tmp/boost -DBOOST_LIBRARYDIR=/tmp/boost/stage/lib -DWITHOUT_SERVERS=1 || exit 1;
      sudo make || exit 1;
    fi
  #
  # Install OSX
  #
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cmake ../ -G"Xcode" -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${COMPILE_OPTIONS} -DWITH_COVERAGE=1 -DWITH_TESTS=1 -DWITHOUT_SERVERS=1 || exit 1;
      sudo xcodebuild -target install -config $BUILD_TYPE install || exit 1;
    fi
  - popd;
  #
  # Unit Testing
  #
  - pushd build/bin/${BUILD_TYPE}/test;
  - for TARGET in *;
    do
      if [ -f "$TARGET" ]; then
        echo "Running ${TARGET}...";
        sudo ./${TARGET} || exit 1;
      fi;
    done;
  - popd;
  - sudo rm -rf build;
  - mkdir build;
  - pushd build;
  - echo "Initiating Horizon build...";
  #
  # Deploy Linux
  #
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cmake ../ -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${COMPILE_OPTIONS} -DBOOST_INCLUDEDIR=/tmp/boost -DBOOST_LIBRARYDIR=/tmp/boost/stage/lib || exit 1;
      sudo make install || exit 1;
    fi
  #
  # Deploy OSX
  #
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        cmake ../ -G"Xcode" -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${COMPILE_OPTIONS} || exit 1;
        sudo xcodebuild -target install -config $BUILD_TYPE install || exit 1;
    fi
  # - pushd bin/${BUILD_TYPE};
  # - sudo cp config/auth-server.lua.dist config/auth-server.lua;
  # - sudo cp config/char-server.lua.dist config/char-server.lua;
  # - sudo cp config/zone-server.lua.dist config/zone-server.lua;
  # - sudo ./auth --with-config="config/auth-server.lua" --test-run || exit 1;
  # - sudo ./char --with-config="config/char-server.lua"  --test-run || exit 1;
  # - sudo ./zone --with-config="config/zone-server.lua"  --test-run || exit 1;