name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  MYSQL_PASSWORD: horizon
  MYSQL_USERNAME: root
  MYSQL_DATABASE: horizon
  MYSQL_HOSTNAME: localhost

jobs:
  Debian-GCC-Libraries:
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DWITHOUT_SERVERS=true
        cmake --build ${{github.workspace}}/build
  Debian-GCC-Tests-Tools:
    needs: Debian-GCC-Libraries
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DWITH_TESTS=true -DWITH_TOOLS=true -DWITHOUT_SERVERS=true
        cmake --build ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --target install
  Debian-GCC-ALL-ASAN:
    needs: Debian-GCC-Tests-Tools
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DWITH_TESTS=true -DWITH_TOOLS=true -DWITH_ASAN=true
        cmake --build ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --target install
        files=$(find ${{github.workspace}}/src/Tests -type f -iname "*Test.cpp");
        for f in ${files[@]};
        do
          t=$(basename ${f::-4});
          /"${{github.workspace}}/build/bin/Debug/test/${t}";
        done
  Debian-GCC-Run-ASAN:
    needs: Debian-GCC-ALL-ASAN
    runs-on: Debian
    steps: 
    - name: Run
      run: |
        cp ${{github.workspace}}/config ${{github.workspace}}/build/bin/Debug/config -r
        cp ${{github.workspace}}/db ${{github.workspace}}/build/bin/Debug/db -r
        cp ${{github.workspace}}/scripts ${{github.workspace}}/build/bin/Debug/scripts -r
        cd ${{github.workspace}}/build/bin/Debug
        ./auth --with-config="config/auth-server.lua.dist" --test-run
        ./char --with-config="config/char-server.lua.dist" --test-run
        ./zone --with-config="config/zone-server.lua.dist" --test-run
  Debian-GCC-ALL-TSAN:
    needs: Debian-GCC-Tests-Tools
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DWITH_TESTS=true -DWITH_TOOLS=true -DWITH_TSAN=true
        cmake --build ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --target install
  Debian-GCC-Run-TSAN:
    needs: Debian-GCC-ALL-TSAN
    runs-on: Debian
    steps: 
    - name: Run
      run: |
        cp ${{github.workspace}}/config ${{github.workspace}}/build/bin/Debug/config -r
        cp ${{github.workspace}}/db ${{github.workspace}}/build/bin/Debug/db -r
        cp ${{github.workspace}}/scripts ${{github.workspace}}/build/bin/Debug/scripts -r
        cd ${{github.workspace}}/build/bin/Debug
        ./auth --with-config="config/auth-server.lua.dist" --test-run
        ./char --with-config="config/char-server.lua.dist" --test-run
        ./zone --with-config="config/zone-server.lua.dist" --test-run
  Debian-GCC-Servers:
    needs: [ Debian-GCC-Run-TSAN, Debian-GCC-Run-ASAN ]
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++"
        cmake --build ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --target install
  Debian-GCC-Upload-Artifact:
    needs: Debian-GCC-Servers
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/upload-artifact@v3
      with: 
        name: artifacts bin
        path: ${{github.workspace}}\build\bin\Debug\**\*
  Debian-Clang-Libraries:
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DWITHOUT_SERVERS=true
        cmake --build ${{github.workspace}}/build
  Debian-Clang-Tests-Tools:
    needs: Debian-Clang-Libraries
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DWITH_TESTS=true -DWITH_TOOLS=true -DWITHOUT_SERVERS=true
        cmake --build ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --target install
        files=$(find ${{github.workspace}}/src/Tests -type f -iname "*Test.cpp");
        for f in ${files[@]};
        do
          t=$(basename ${f::-4});
          /"${{github.workspace}}/build/bin/Debug/test/${t}";
        done
  Debian-Clang-ALL-ASAN:
    needs: Debian-Clang-Tests-Tools
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DWITH_TESTS= -DWITH_ASAN=true
        cmake --build ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --target install
  Debian-Clang-Run-ASAN:
    needs: Debian-Clang-ALL-ASAN
    runs-on: Debian
    steps: 
    - name: Run
      run: |
        cp ${{github.workspace}}/config ${{github.workspace}}/build/bin/Debug/config -r
        cp ${{github.workspace}}/db ${{github.workspace}}/build/bin/Debug/db -r
        cp ${{github.workspace}}/scripts ${{github.workspace}}/build/bin/Debug/scripts -r
        cd ${{github.workspace}}/build/bin/Debug
        ./auth --with-config="config/auth-server.lua.dist" --test-run
        ./char --with-config="config/char-server.lua.dist" --test-run
        ./zone --with-config="config/zone-server.lua.dist" --test-run
  Debian-Clang-ALL-TSAN:
    needs: Debian-Clang-Tests-Tools
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DWITH_TSAN=true
        cmake --build ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --target install
  Debian-Clang-Run-TSAN:
    needs: Debian-Clang-ALL-TSAN
    runs-on: Debian
    steps: 
    - name: Run
      run: |
        cp ${{github.workspace}}/config ${{github.workspace}}/build/bin/Debug/config -r
        cp ${{github.workspace}}/db ${{github.workspace}}/build/bin/Debug/db -r
        cp ${{github.workspace}}/scripts ${{github.workspace}}/build/bin/Debug/scripts -r
        cd ${{github.workspace}}/build/bin/Debug
        ./auth --with-config="config/auth-server.lua.dist" --test-run
        ./char --with-config="config/char-server.lua.dist" --test-run
        ./zone --with-config="config/zone-server.lua.dist" --test-run
  Debian-Clang-Servers:
    needs: [ Debian-Clang-Run-ASAN, Debian-Clang-Run-TSAN ]
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure & Build
      run: |
        cmake -B"${{github.workspace}}/build" -S"${{github.workspace}}" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++"
        cmake --build ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --target install
  Debian-Clang-Upload-Artifact:
    needs: Debian-Clang-Servers
    runs-on: Debian
    steps:
    - name: Checkout
      uses: actions/upload-artifact@v3
      with: 
        name: artifacts bin
        path: ${{github.workspace}}\build\bin\Debug\**\*

  Windows-Libraries:
    runs-on: Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: ./horizon.sh build-only-libraries -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows

  Windows-Tests:
    needs: Windows-Libraries
    runs-on: Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build
      run: ./horizon.sh build-tests -DCMAKE_INSTALL_PREFIX="${{github.workspace}}\build" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows
    
    - name: Run
      run: ./horizon.sh run-tests "build\test\Release"
      
  Windows-Tools:
    needs: Windows-Tests
    runs-on: Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: ./horizon.sh build-tools -DCMAKE_INSTALL_PREFIX="${{github.workspace}}\build" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows
    
  Windows-Servers:
    needs: [ Windows-Tests, Windows-Tools, Windows-Libraries ]
    runs-on: Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - name: Configure Step & Build
      run: ./horizon.sh build ${{github.workspace}}\build -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX="${{github.workspace}}\build" 

  Windows-Upload-Artifact:
    needs: Windows-Servers
    runs-on: Windows
    steps:
    - name: Checkout
      uses: actions/upload-artifact@v3
      with: 
        name: artifacts bin
        path: ${{github.workspace}}\build\bin\Release\**\*
    # Uncomment when we have some more information on why its failing?  
    #- name: Run Auth
    #  working-directory: ${{github.workspace}}\build\bin\Release
    #  run: |
    #    ./auth.exe --with-config="config\auth-server.lua" --test-run 
    #    ./char.exe --with-config="config\char-server.lua" --test-run
    #    ./zone.exe --with-config="config\zone-server.lua" --test-run 
